name: geoflutterfire3
description: GeoFlutterFire3 is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 1.0.0
homepage: https://github.com/KumaloWilson/GeoFlutterFire3

environment:
  sdk: "^3.6.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.4.4
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
